version: '2'
services:
  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

  fluentd:
    build: fluentd
    ports:
      - 24224:24224
    links:
      - elasticsearch
    environment:
      ES_SCHEME: http
      ES_HOST: elasticsearch
      ES_PORT: 9200

  producer:
    build: producer
    links:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: 'docker.producer'
